[package]
name = "relo"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.39", features = ["derive"] }
env_logger = "0.11.8"
log = "0.4.27"
anyhow = "1.0.93"
walkdir = "2.5.0"
rayon = "1.10.0"

[dev-dependencies]
tempfile = "3.14.0"
